const dogs = [
  {
    name: "Rex",
    avatar: "images/dog-black.jpg",
    age: 25,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Chews",
    avatar: "images/dog-chews.jpg",
    age: 20,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Greyhound",
    avatar: "images/dog-greyhound.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Grumpy",
    avatar: "images/dog-grumpy.jpg",
    age: 22,
    bio: "We've been waiting for this one",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Rex",
    avatar: "images/dog-rex.jpg",
    age: 28,
    bio: " When you know exactly what you're doing",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Teddy",
    avatar: "images/dog-teddy.jpg",
    age: 18,
    bio: "It's not funny, it's funny, it's not funny, it's funny",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "White",
    avatar: "images/dog-white.jpg",
    age: 35,
    bio: "I think I can hear it too",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];
